language: java
jdk: oraclejdk8
before_install:
- chmod +x gradlew
install: "./gradlew setupCIWorkspace -S"
script: "./gradlew build -S"
notifications:
  slack:
    secure: mvyotvejOmIxUHLNzXKw3oQaOgH2QnoTanomf5+mJqWz0MwLFLcnhDtNdsVQafSUvVQ8rI5AbKYHWXzM/k6JxsUhaTJZBSvm/BaM6feMdd5WGO4Ai/YzdlXOqhVRLtQ9cph96oB8xsPPCvFDqd7+G1OjjXZF5FadYL9Z4YvmQBYXuVLfGzjouWbNRUfuX6i9bxp4Pry2PdsQvibAeJek1m6PVHR1AiB6zxEM4/JP4MChA7B8orAnolLq20Ohv9YXdWTpgtBqGzg9Ui7jwTQ07gmWEZstgsyzNXqsLY4iBjPmD5BhPhbt+/HhMoB4FcfRvDX7kljNtaKQ629ujjJFT70bG75M4BRXPwo21cgAWYXR37fxr8d/wHzW4UiW7sTLynEpwkIiMTctBSWrhooPgjTw0UZCcaWo/ih4lTLe3ifjWacndcS1qB98EVi5Gbkzg1jCGLDMOka5jDghbMhJJJNAx/e90sIST3iD6BT39gOPSr5FvJnY7jLDzzrEfjGLzBxtX60+2tBCIIanXtmtpumc6ZNlD+d7QOFdrVyVGCX/2URlFE43P5tVczKU25gaLPSMDg8EgI/mic1BqLaUqC3pzhPUk5DCCDfimo7TMH27ee00s/fJXseOfmheb7Pux3wMGYQ/zWo+xUab40UslX8BnShyir+GyxIhWE83V2c=
